USE [master]
GO

/****** Object:  Database [TOKEN_GVA_SIT]    Script Date: 5/2/2016 10:49:02 AM ******/
CREATE DATABASE [TOKEN_GVA_SIT]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TOKEN_GVA_SIT', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS2014\MSSQL\DATA\TOKEN_GVA_SIT.mdf' , SIZE = 57344KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'TOKEN_GVA_SIT_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS2014\MSSQL\DATA\TOKEN_GVA_SIT_log.ldf' , SIZE = 149696KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [TOKEN_GVA_SIT] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TOKEN_GVA_SIT].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TOKEN_GVA_SIT] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TOKEN_GVA_SIT] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TOKEN_GVA_SIT] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TOKEN_GVA_SIT] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TOKEN_GVA_SIT] SET ARITHABORT OFF 
GO

ALTER DATABASE [TOKEN_GVA_SIT] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TOKEN_GVA_SIT] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TOKEN_GVA_SIT] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TOKEN_GVA_SIT] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TOKEN_GVA_SIT] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TOKEN_GVA_SIT] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TOKEN_GVA_SIT] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TOKEN_GVA_SIT] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TOKEN_GVA_SIT] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TOKEN_GVA_SIT] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TOKEN_GVA_SIT] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TOKEN_GVA_SIT] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TOKEN_GVA_SIT] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TOKEN_GVA_SIT] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TOKEN_GVA_SIT] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TOKEN_GVA_SIT] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TOKEN_GVA_SIT] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TOKEN_GVA_SIT] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [TOKEN_GVA_SIT] SET  MULTI_USER 
GO

ALTER DATABASE [TOKEN_GVA_SIT] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TOKEN_GVA_SIT] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TOKEN_GVA_SIT] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TOKEN_GVA_SIT] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [TOKEN_GVA_SIT] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TOKEN_GVA_SIT] SET  READ_WRITE 
GO


