/*
	Script to truncate table of TECORE
*/

TRUNCATE TABLE TECORE.APIAUTH;

TRUNCATE TABLE TECORE.Configuration;

TRUNCATE TABLE TECORE.MonitoringJobs;

TRUNCATE TABLE TECORE.SeedDateTime1;

TRUNCATE TABLE TECORE.SeedDateTime2;

TRUNCATE TABLE TECORE.SeedDateTime3;

TRUNCATE TABLE TECORE.SeedInteger1;

TRUNCATE TABLE TECORE.SeedInteger2;

TRUNCATE TABLE TECORE.SeedInteger3;

TRUNCATE TABLE TECORE.SeedString1;

TRUNCATE TABLE TECORE.SeedString2;

TRUNCATE TABLE TECORE.SeedString3;

TRUNCATE TABLE TECORE.Table_Set;

TRUNCATE TABLE TECORE.TokenDecision;